on:
  push:
    branches: [master]

name: WEB

defaults:
  run:
    working-directory: web

jobs:
  build:
    name: Build, Tests and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    # - name: Run lint
    #   run: npm run lint
